server:
  port: 9412

spring:
  application:
    name: easycard-zipkin-server-alibaba
  cloud:
    # 配置nacos
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        namespace: easycard-dev

management:
  metrics:
    web:
      server:
        # 关闭⾃动检测请求 这里不关闭的话，会报一些错误。
        auto-time-requests: false
