server:
  port: 8091

spring:
  application:
    name: easycard-service-card-alibaba
  #zipkin配置
  zipkin:
    # zipkin server的请求地址
    base-url: http://127.0.0.1:9412
    sender:
      # web 客户端将踪迹⽇志数据通过⽹络请求的⽅式传送到服务端
      # kafka/rabbit 客户端将踪迹⽇志数据传递到mq进⾏中转
      type: web
  #sleuth配置
  sleuth:
    sampler:
      # 采样率 1 代表100%全部采集 ，默认0.1 代表10% 的请求踪迹数据会被采集
      # ⽣产环境下，请求量⾮常⼤，没有必要所有请求的踪迹数据都采集分析，
      # 对于⽹络包括server端压⼒都是⽐较⼤的，可以配置采样率采集⼀定⽐例的请求的踪迹数据进⾏分析即可
      probability: 1
  cloud:
    # 配置nacos
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        namespace: easycard-dev
      config:
        # ${prefix}-${spring.profile.active}.${file-extension}
        # 分组，默认DEFAULT_GROUP
        group: DEFAULT_GROUP
        # 配置中心地址
        server-addr: 127.0.0.1:8848
        # 命名空间
        namespace: easycard-dev
        # 文件格式
        file-extension: yaml

#日记配置
logging:
  #配置日志级别
  level:
    #分布式链路追踪日志级别配置
    org.springframework.web.servlet.DispatcherServlet: debug
    org.springframework.cloud.sleuth: debug
