server:
  port: 8761

spring:
  application:
    #定义应用名称，会在Eureka中作为服务的id标识（serviceId）
    name: easycard-eureka-server

eureka:
  instance:
    #集群模式下， 这里需要填写主机名
    hostname: localhost
  client:
    service-url:
      #客户端与Eureka Server交互的地址，如果是集群，也需写其他的地址，使用英文逗号间隔即可
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
    #注册自己，默认是true
    register-with-eureka: false
    #自己就是Server，不需要从Eureka Server获取服务信息。默认是true
    fetch-registry: false
