server:
  port: 8081

spring:
  application:
    name: easycard-service-card
  #zipkin配置
  zipkin:
    # zipkin server的请求地址
    base-url: http://127.0.0.1:9411
    sender:
      # web 客户端将踪迹⽇志数据通过⽹络请求的⽅式传送到服务端
      # kafka/rabbit 客户端将踪迹⽇志数据传递到mq进⾏中转
      type: web
  #sleuth配置
  sleuth:
    sampler:
      # 采样率 1 代表100%全部采集 ，默认0.1 代表10% 的请求踪迹数据会被采集
      # ⽣产环境下，请求量⾮常⼤，没有必要所有请求的踪迹数据都采集分析，
      # 对于⽹络包括server端压⼒都是⽐较⼤的，可以配置采样率采集⼀定⽐例的请求的踪迹数据进⾏分析即可
      probability: 1

#向Eureka服务中⼼注册服务
eureka:
  instance:
    hostname: localhost
    #配置使用IP注册，否则会使用主机名注册。
    prefer-ip-address: true
    #自定义实例在Eureka中显示的服务名称
    instance-id: ${spring.cloud.client.ip-address}:${spring.application.name}:${server.port}
    #服务提供者续约配置，续约间隔时间，默认为30秒
    lease-renewal-interval-in-seconds: 30
    #租约到期时间，默认为90秒。服务超过90秒没有发生心跳（报活），EurekaServer会将服务从列表中移除
    lease-expiration-duration-in-seconds: 90
  client:
    service-url:
      #Eureka注册中心注册链接,多个使用英文逗号间隔
      defaultZone: http://${eureka.instance.hostname}:8761/eureka/
    #服务消费者每隔多久拉取一次服务列表，默认30秒拉取一次
    registry-fetch-interval-seconds: 30

#日记配置
logging:
  #配置日志级别
  level:
    #分布式链路追踪
    org.springframework.web.servlet.DispatcherServlet: debug
    org.springframework.cloud.sleuth: debug
